name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.0.0
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: Build and push gateway-device_manager
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          platforms: linux/arm/v7
          tags: |
            ${{ env.REGISTRY }}/lorabridge/gateway-device_manager:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/lorabridge/gateway-device_manager:latest
          cache-to: type=inline
